name: Process Chrome OS recovery images
concurrency: main

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '21 * * * *'

env:
  PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION: python
jobs:
  process-recovery:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Ensure we're at ToT
        run: |
          git config pull.rebase true
          git config --global pull.ff only
          git pull
          git pull --rebase

      - name: Install requirements
        run: pip3 install -r scripts/requirements.txt

      - name: Generate Chrome/OS version maps
        run: python3 scripts/generate_chromeos2chrome_versionmap.py

      - name: Process latest recovery.json
        run: python3 scripts/process-latest-recovery.py

      - name: Analyze recovery images
        run: python3 scripts/analyze_image_details.py

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add --all
          git add data/*
          git diff --quiet && git diff --staged --quiet || git commit -am 'Add recovery changes [ci skip]'

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
